import "@mantine/core/styles.css";
import "@mantine/nprogress/styles.css";
import "@mantine/notifications/styles.css";

import "@styles/base.css";

import type { Metadata } from "next";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import AppLayout from "@layout/AppLayout";
import { THEME_MANTINE } from "@utils/resources/theme";
import NProgress from "@module/NProgress/NProgress";
import { NavigationProgress } from "@mantine/nprogress";
import { Notifications } from "@mantine/notifications";
import { Suspense } from "react";
// import NProgress from "@module/NProgress/NProgress";
// import { Suspense } from "react";
// import { NavigationProgress } from "@mantine/nprogress";

export const metadata: Metadata = {
  title: "Main Title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.bunny.net" />
        <link
          href="https://fonts.bunny.net/css?family=inter:200,300,400,500,600,700,800,900"
          rel="stylesheet"
        />

        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <MantineProvider theme={THEME_MANTINE} defaultColorScheme="dark">
          <Notifications />
          <NavigationProgress />

          <Suspense fallback={null}>
            <NProgress />
          </Suspense>

          <AppLayout>{children}</AppLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
